<a href="https://colab.research.google.com/github/Nishaddeshmukh/GENAI/blob/main/GenAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
dir(__builtin__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BaseExceptionGroup',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EncodingWarning',
 'EnvironmentError',
 'Exception',
 'ExceptionGroup',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'Runti

**`Numpy practice set `**

In [3]:
import numpy as np

arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
arr= np.zeros(2,dtype = int)
print(arr)

[0 0]


In [11]:
arr= np.zeros(2,dtype = int)
print(arr)
arr= np.zeros(2,dtype = float)
print(arr)

[0 0]
[0. 0.]


In [16]:
arr=np.ones(2,dtype = int)
print(arr)
arr2=np.ones(2,dtype = str)
print(arr2)

arr= np.ones(2)        #default datatype is float for np.ones()
print(arr)

[1 1]
['1' '1']
[1. 1.]


In [19]:
# np.empty()
# Description: Creates an uninitialized array.
# Example:
import numpy as np
arr1= np.empty([1, 1])   #-> 1x1
arr2 = np.empty((3,7))   #3x7 mat
print(arr1)
print(arr2)


[[3.4e-321]]
[[3.26670108e-316 0.00000000e+000 4.32453723e-096 2.14027814e+161
  1.47762371e+248 4.30625279e-096 4.82337723e+228]
 [1.00552232e-070 5.14776014e-062 7.35365846e-043 4.75376121e-037
  4.30513777e-096 1.16097020e-028 3.21142670e-322]
 [6.75138464e-310 6.75138464e-310 1.04917184e-153 9.08366791e+223
  6.14415221e-144 6.75138464e-310 1.10670705e-321]]


In [22]:
#np.arrange()

arr = np.arange(0,10,2)  # 0 to 10  with equal interval 2
print(arr)

[0 2 4 6 8]


In [25]:
arr = np.linspace(2,10,10)  # creates an array with evenly spaced values
print(arr)

[ 2.          2.88888889  3.77777778  4.66666667  5.55555556  6.44444444
  7.33333333  8.22222222  9.11111111 10.        ]


In [28]:
arr = np.eye(3)
print(arr)            #identity matrix of 3x3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
arr=np.random.rand(3,3)   #
print(arr)

arr1=np.random.randint(0,1005,(3,3))   #   range -> 0 to 1005 and mat will be 3x3
print(arr1)

[[0.79427939 0.40803871 0.22614929]
 [0.93889313 0.03154731 0.69004017]
 [0.35353831 0.09314301 0.19681161]]
[[308 593 795]
 [881   2 283]
 [991 211 277]]


In [37]:



# np.reshape()
# Description: Reshapes an array.
# Example:
arr = np.array([1, 2, 3, 4]).reshape(2, 2)
print(arr)
print('\n')

# np.transpose()
# Description: Transposes an array.
# Example:
arr = np.array([[1, 2], [3, 4]]).transpose()
print(arr)

print('\n')


# np.concatenate()
# Description: Concatenates two arrays.
# Example:
arr = np.concatenate(([1, 2], [3, 4]))
print(arr)
print('\n')




[[1 2]
 [3 4]]


[[1 3]
 [2 4]]


[1 2 3 4]




In [41]:
# np.vstack()
# Description: Stacks arrays vertically.

# Example:
import numpy as np
a = np.array([(1,2,3,4),(3,4,5,5),(1,2,3,5)])
b = np.array([(1,2,3,4),(3,4,5,5),(1,2,3,6)])


# arr = np.vstack(([1, 2], [3, 4]))
# print(arr)
#vertical stacking
print(a)
print("Shape of array a is ", np.shape(a))
print(b)
print ("Shape of array b is ",np.shape(b))
print(np.vstack((a,b)))
print("Shape of arry after vstack is ", np.vstack((a,b)).shape)


#horizontal  stacking
print('\n')
print(a)
print(b)
print (np.shape(a))
print (np.shape(b)) #jfhgjfhg
print(np.hstack((a,b)).shape)
print(np.hstack((a,b)))



[[1 2 3 4]
 [3 4 5 5]
 [1 2 3 5]]
Shape of array a is  (3, 4)
[[1 2 3 4]
 [3 4 5 5]
 [1 2 3 6]]
Shape of array b is  (3, 4)
[[1 2 3 4]
 [3 4 5 5]
 [1 2 3 5]
 [1 2 3 4]
 [3 4 5 5]
 [1 2 3 6]]
Shape of arry after vstack is  (6, 4)


[[1 2 3 4]
 [3 4 5 5]
 [1 2 3 5]]
[[1 2 3 4]
 [3 4 5 5]
 [1 2 3 6]]
(3, 4)
(3, 4)
(3, 8)
[[1 2 3 4 1 2 3 4]
 [3 4 5 5 3 4 5 5]
 [1 2 3 5 1 2 3 6]]


In [43]:
import numpy as np

# Original array
data = np.array([1, 2, 3, 4, 5])  # Example with 5 elements

# Desired shape (e.g., 2x3, which requires 6 elements)
target_shape = (4, 4)

# Use np.resize to fit the target shape
reshaped_array = np.resize(data, target_shape)         # here target elements will get repeated

print("Reshaped Array:")
print(reshaped_array)

Reshaped Array:
[[1 2 3 4]
 [5 1 2 3]
 [4 5 1 2]
 [3 4 5 1]]


In [44]:
# np.split()
# Description: Splits an array into multiple sub-arrays.
# Example:
arr = np.split(np.array([1, 2, 3, 4]), 2)          # splitting into 2 numpy array
print(arr)

[array([1, 2]), array([3, 4])]


In [46]:
# np.hsplit()
# Description: Splits an array into multiple sub-arrays horizontally.
# Example:
arr = np.hsplit(np.array([[1, 2], [3, 4]]), 2)
print(arr)

print('\n')
# np.vsplit()
# Description: Splits an array into multiple sub-arrays vertically.
# Example:
arr = np.vsplit(np.array([[1, 2], [3, 4]]), 2)
print(arr)


[array([[1],
       [3]]), array([[2],
       [4]])]


[array([[1, 2]]), array([[3, 4]])]


**DIMENSIONS CHANGIG CODE**

In [47]:
#dimension changes
#a = np.array(([1,2,3,4],[5,6,7,8]))
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print('first')
print(a.shape)
#print(a.shape())
a = a.reshape(4,2)
#a = a.reshape(-1)
#a = a.reshape(1,8)
print('second')
print(a)
print(a.shape)


[[1 2 3 4]
 [5 6 7 8]]
first
(2, 4)
second
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [49]:

print(a)
aa = a.repeat(3, 0)           #--> repeat 3 times of 0Th axis
# # a = a.repeat(0, 3)
print(aa)
print(aa.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]
 [5 6]
 [5 6]
 [5 6]
 [7 8]
 [7 8]
 [7 8]]
(12, 2)


In [50]:

print(a)
a = a.repeat(3, 1)    #--> repeat 3 times of 0Th axis
print(a)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]
 [5 5 5 6 6 6]
 [7 7 7 8 8 8]]
(4, 6)


In [51]:
import numpy as np

# Original array of shape (3, 3, 4)
array_3d = np.random.randint(0, 100, (3, 3, 4))     # range -> 0 to 100 , shape (3, 3, 4) --> 3 of 3x4
print("Original 3D array:")
print(array_3d)
print("Original shape:", array_3d.shape)

# Repeat the array along the first axis to achieve shape (6, 3, 4)
new_array = np.tile(array_3d, (2, 1, 1))  # Repeat only along the first axis
print(new_array)
print("\nNew 3D array after repeating along the first axis:")
print(new_array)
print("New shape:", new_array.shape)

Original 3D array:
[[[53 14 52 36]
  [12  6  8 42]
  [30 42  4 25]]

 [[78 18 67 25]
  [10 92 32 58]
  [42 12 29  8]]

 [[16  8 26 63]
  [98 18  8 17]
  [74 12 59 46]]]
Original shape: (3, 3, 4)
[[[53 14 52 36]
  [12  6  8 42]
  [30 42  4 25]]

 [[78 18 67 25]
  [10 92 32 58]
  [42 12 29  8]]

 [[16  8 26 63]
  [98 18  8 17]
  [74 12 59 46]]

 [[53 14 52 36]
  [12  6  8 42]
  [30 42  4 25]]

 [[78 18 67 25]
  [10 92 32 58]
  [42 12 29  8]]

 [[16  8 26 63]
  [98 18  8 17]
  [74 12 59 46]]]

New 3D array after repeating along the first axis:
[[[53 14 52 36]
  [12  6  8 42]
  [30 42  4 25]]

 [[78 18 67 25]
  [10 92 32 58]
  [42 12 29  8]]

 [[16  8 26 63]
  [98 18  8 17]
  [74 12 59 46]]

 [[53 14 52 36]
  [12  6  8 42]
  [30 42  4 25]]

 [[78 18 67 25]
  [10 92 32 58]
  [42 12 29  8]]

 [[16  8 26 63]
  [98 18  8 17]
  [74 12 59 46]]]
New shape: (6, 3, 4)


In [52]:
# np.sort()
# Description: Sorts an array.
# Example:
arr = np.sort(np.array([3, 1, 2]))
print(arr)


[1 2 3]


In [53]:



# np.argsort()
# Description: Returns the indices that would sort an array.
# Example:
arr = np.argsort(np.array([3, 1, 2]))
#                          0  1  2
print(arr)


[1 2 0]
