<a href="https://colab.research.google.com/github/Nishaddeshmukh/GENAI/blob/main/numpy_functions_complex_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# np.tanh()
# Description: Calculates the hyperbolic tangent element-wise.
# Example:
arr = np.tanh(np.array([0, np.pi/4, np.pi/2]))
print(arr)


[0.         0.6557942  0.91715234]


In [ ]:
# np.arcsinh()
# Description: Inverse hyperbolic sine element-wise.
# Example:
arr = np.arcsinh(np.array([0, np.pi/2, np.pi]))
print(arr)


[0.         1.23340312 1.86229574]


In [ ]:
# np.arccosh()
# Description: Inverse hyperbolic cosine element-wise.
# Example:
arr = np.arccosh(np.array([1, np.pi/2, np.pi]))
print(arr)


[0.         1.02322748 1.81152627]


In [ ]:
# np.arctanh()
# Description: Inverse hyperbolic tangent element-wise.
# Example:
arr = np.arctanh(np.array([0, 0.5, 0.9]))
print(arr)


[0.         0.54930614 1.47221949]


In [ ]:
# np.deg2rad()
# Description: Converts angles from degrees to radians.
# Example:
arr = np.deg2rad(np.array([0, 45, 90]))
print(arr)


[0.         0.78539816 1.57079633]


In [ ]:
# np.rad2deg()
# Description: Converts angles from radians to degrees.
# Example:
arr = np.rad2deg(np.array([0, np.pi/4, np.pi/2]))
print(arr)


[ 0. 45. 90.]


In [ ]:
# np.unwrap()
# Description: Unwraps the phase angle by changing deltas between values to 2*pi complement.
# Example:
arr = np.unwrap(np.array([0, np.pi, np.pi + 0.1, np.pi*2]))
print(arr)


[0.         3.14159265 3.24159265 6.28318531]


In [ ]:
# np.fft.rfftn()
# Description: Computes the N-dimensional discrete Fourier Transform for real input.
# Example:
arr = np.fft.rfftn(np.array([[1, 2], [3, 4]]))
print(arr)


[[10.+0.j -2.+0.j]
 [-4.+0.j  0.+0.j]]


In [ ]:
# np.fft.irfftn()
# Description: Computes the inverse of the N-dimensional discrete Fourier Transform for real input.
# Example:
arr = np.fft.irfftn(np.array([[1, 2], [3, 4]]))
print(arr)


[[ 2.5 -0.5]
 [-1.   0. ]]


In [ ]:
# np.exp2()
# Description: Calculates 2 raised to the power of input.
# Example:
arr = np.exp2(np.array([1, 2, 3]))
print(arr)


[2. 4. 8.]


In [ ]:
# np.expm1()
# Description: Calculates exp(x) - 1 for all elements in the array.
# Example:
arr = np.expm1(np.array([1, 2, 3]))
print(arr)


[ 1.71828183  6.3890561  19.08553692]


In [ ]:
# np.log1p()
# Description: Calculates log(1 + x) for all elements in the array.
# Example:
arr = np.log1p(np.array([0, 1, 2]))
print(arr)


[0.         0.69314718 1.09861229]


In [ ]:
# np.sqrt()
# Description: Calculates the square root element-wise.
# Example:
arr = np.sqrt(np.array([1, 4, 9]))
print(arr)


[1. 2. 3.]


In [ ]:
# np.cbrt()
# Description: Calculates the cube root element-wise.
# Example:
arr = np.cbrt(np.array([1, 8, 27]))
print(arr)


[1. 2. 3.]


In [ ]:
# np.square()
# Description: Calculates the square of each element.
# Example:
arr = np.square(np.array([2, 3, 4]))
print(arr)


[ 4  9 16]


In [ ]:
# np.signbit()
# Description: Returns element-wise True where signbit is set (x < 0).
# Example:
arr = np.signbit(np.array([-1, 0, 1]))
print(arr)


[ True False False]


In [ ]:
# np.copysign()
# Description: Changes the sign of elements in x1 to match the sign of elements in x2.
# Example:
arr = np.copysign(np.array([-1, 0, 1]), -1)
print(arr)


[-1. -0. -1.]


In [ ]:
# np.spacing()
# Description: Returns the distance between x and the nearest adjacent number.
# Example:
arr = np.spacing(1)
print(arr)


2.220446049250313e-16


In [ ]:
# np.nextafter()
# Description: Returns the next floating-point value after x1 towards x2.
# Example:
arr = np.nextafter(np.array([1.0, 2.0]), np.array([2.0, 3.0]))
print(arr)


[1. 2.]


In [ ]:
# np.fmod()
# Description: Returns the element-wise remainder of the division.
# Example:
arr = np.fmod(np.array([1, 2, 3]), 2)
print(arr)


[1 0 1]


In [ ]:
# np.remainder()
# Description: Returns the element-wise remainder of the division (same as mod).
# Example:
arr = np.remainder(np.array([1, 2, 3]), 2)
print(arr)


[1 0 1]


In [ ]:
# np.modf()
# Description: Returns the fractional and integer parts of the array.
# Example:
frac, integer = np.modf(np.array([1.5, 2.3, 3.8]))
print(frac)
print(integer)


[0.5 0.3 0.8]
[1. 2. 3.]


In [ ]:
# np.isfinite()
# Description: Tests element-wise for finiteness (not infinity or NaN).
# Example:
arr = np.isfinite(np.array([1, 2, np.nan, np.inf]))
print(arr)


[ True  True False False]


In [ ]:
# np.isinf()
# Description: Tests element-wise for positive or negative infinity.
# Example:
arr = np.isinf(np.array([1, 2, np.inf, -np.inf]))
print(arr)


[False False  True  True]


In [ ]:
# np.isnan()
# Description: Tests element-wise for NaN.
# Example:
arr = np.isnan(np.array([1, np.nan, 3]))
print(arr)


[False  True False]
